appName: tellYourSecrets

log_path: "logs/"
flask_app: app.py

firebase_credentials: "/Users/otmanesabir/tellyoursecrets-pro-firebase-adminsdk.json"

crawler_settings:
  review_limit: 3
  app_limit: 3

selenium:
  driver_path: "/usr/local/bin/chromedriver"
  headless: True